postgres:
  container_name: postgres
  restart: always
  image: postgres:12.9-alpine
  volumes:
    - ./data:/var/lib/postgresql/data
  ports:
    - 5432:5432
  environment:
    - POSTGRES_PASSWORD=password
